openapi: "3.0.2"
info:
  title: Empathy
  version: "1.0"

servers:
  - url: https://empahty.vercel.app/api
    description: Production server (uses live data)
  - url: http://localhost:3000/api
    description: localhost

tags:
  - name: users
  - name: friends

paths:
  /users:
    $ref: "./resources/users.yaml"
  /users/{userId}:
    $ref: "./resources/user.yaml"
  /users/friends:
    $ref: "./resources/friends.yaml"
  /users/friends/{friendId}:
    $ref: "./resources/friend.yaml"
  /me:
    $ref: "./resources/me.yaml"
  /health:
    get:
      operationId: checkHealth
      responses:
        "200":
          description: OK
        "404":
          description: NOT FOUND
